/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.40.0
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export { PredicateExampleAbi__factory } from './factories/PredicateExampleAbi__factory';
